# coding: utf-8

"""
    Severalnines ClusterControl REST API (V2)

    REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

    The version of the OpenAPI document: OpenAPI specification v1.0.0
    Contact: sales@severalnines.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_cc_client.models.clusters_account import ClustersAccount
from openapi_cc_client.models.clusters_configuration_inner import ClustersConfigurationInner
from openapi_cc_client.models.clusters_database import ClustersDatabase
from typing import Optional, Set
from typing_extensions import Self

class Clusters(BaseModel):
    """
    Clusters
    """ # noqa: E501
    operation: StrictStr
    cluster_id: Optional[StrictInt] = None
    cluster_name: Optional[StrictStr] = None
    with_hosts: Optional[StrictBool] = None
    with_sheet_info: Optional[StrictBool] = None
    configuration: Optional[List[ClustersConfigurationInner]] = None
    account: Optional[ClustersAccount] = None
    filter_strings: Optional[StrictStr] = None
    limit: Optional[StrictInt] = None
    offset: Optional[StrictInt] = None
    database: Optional[ClustersDatabase] = None
    nodes: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["operation", "cluster_id", "cluster_name", "with_hosts", "with_sheet_info", "configuration", "account", "filter_strings", "limit", "offset", "database", "nodes"]

    @field_validator('operation')
    def operation_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['getallclusterinfo', 'getclusterinfo', 'getConfig', 'setConfig', 'createAccount', 'getAccounts', 'deleteAccount', 'grantPrivileges', 'revokePrivileges', 'revokeAllPrivileges', 'getSqlProcesses', 'getTopQueries', 'createDatabase', 'ping', 'availableUpgrades']):
            raise ValueError("must be one of enum values ('getallclusterinfo', 'getclusterinfo', 'getConfig', 'setConfig', 'createAccount', 'getAccounts', 'deleteAccount', 'grantPrivileges', 'revokePrivileges', 'revokeAllPrivileges', 'getSqlProcesses', 'getTopQueries', 'createDatabase', 'ping', 'availableUpgrades')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Clusters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in configuration (list)
        _items = []
        if self.configuration:
            for _item_configuration in self.configuration:
                if _item_configuration:
                    _items.append(_item_configuration.to_dict())
            _dict['configuration'] = _items
        # override the default output from pydantic by calling `to_dict()` of account
        if self.account:
            _dict['account'] = self.account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of database
        if self.database:
            _dict['database'] = self.database.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Clusters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operation": obj.get("operation"),
            "cluster_id": obj.get("cluster_id"),
            "cluster_name": obj.get("cluster_name"),
            "with_hosts": obj.get("with_hosts"),
            "with_sheet_info": obj.get("with_sheet_info"),
            "configuration": [ClustersConfigurationInner.from_dict(_item) for _item in obj["configuration"]] if obj.get("configuration") is not None else None,
            "account": ClustersAccount.from_dict(obj["account"]) if obj.get("account") is not None else None,
            "filter_strings": obj.get("filter_strings"),
            "limit": obj.get("limit"),
            "offset": obj.get("offset"),
            "database": ClustersDatabase.from_dict(obj["database"]) if obj.get("database") is not None else None,
            "nodes": obj.get("nodes")
        })
        return _obj


