# coding: utf-8

"""
    Severalnines ClusterControl REST API (V2)

    REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

    The version of the OpenAPI document: OpenAPI specification v1.0.0
    Contact: sales@severalnines.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_cc_client.models.jobs_job import JobsJob
from typing import Optional, Set
from typing_extensions import Self

class Jobs(BaseModel):
    """
    Creating and manipulating jobs, reading information about jobs
    """ # noqa: E501
    operation: StrictStr
    cluster_id: Optional[StrictInt] = None
    job_id: Optional[StrictInt] = None
    signal: Optional[StrictInt] = None
    ascending: Optional[StrictBool] = None
    limit: Optional[StrictInt] = None
    offset: Optional[StrictInt] = None
    log_level: Optional[StrictStr] = None
    job: Optional[JobsJob] = None
    __properties: ClassVar[List[str]] = ["operation", "cluster_id", "job_id", "signal", "ascending", "limit", "offset", "log_level", "job"]

    @field_validator('operation')
    def operation_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['createJobInstance', 'updateJobInstance', 'deleteJobInstance', 'killJobInstance', 'cloneJobInstance', 'getJobInstance', 'getJobInstances', 'getJobLog']):
            raise ValueError("must be one of enum values ('createJobInstance', 'updateJobInstance', 'deleteJobInstance', 'killJobInstance', 'cloneJobInstance', 'getJobInstance', 'getJobInstances', 'getJobLog')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Jobs from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of job
        if self.job:
            _dict['job'] = self.job.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Jobs from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operation": obj.get("operation"),
            "cluster_id": obj.get("cluster_id"),
            "job_id": obj.get("job_id"),
            "signal": obj.get("signal"),
            "ascending": obj.get("ascending"),
            "limit": obj.get("limit"),
            "offset": obj.get("offset"),
            "log_level": obj.get("log_level"),
            "job": JobsJob.from_dict(obj["job"]) if obj.get("job") is not None else None
        })
        return _obj


