# coding: utf-8

"""
    Severalnines ClusterControl REST API (V2)

    REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

    The version of the OpenAPI document: OpenAPI specification v1.0.0
    Contact: sales@severalnines.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_cc_client.models.users_group import UsersGroup
from openapi_cc_client.models.users_user import UsersUser
from typing import Optional, Set
from typing_extensions import Self

class Users(BaseModel):
    """
    Users
    """ # noqa: E501
    operation: StrictStr
    create_group: Optional[StrictBool] = None
    new_password: Optional[StrictStr] = None
    old_password: Optional[StrictStr] = None
    group_name: Optional[StrictStr] = None
    replace_primary_group: Optional[StrictBool] = None
    with_tags: Optional[List[StrictStr]] = None
    user: Optional[UsersUser] = None
    group: Optional[UsersGroup] = None
    __properties: ClassVar[List[str]] = ["operation", "create_group", "new_password", "old_password", "group_name", "replace_primary_group", "with_tags", "user", "group"]

    @field_validator('operation')
    def operation_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['createUser', 'getUsers', 'setUser', 'disable', 'deleteUser', 'enable', 'changePassword', 'getKeys', 'addKey', 'deleteKey', 'createGroup', 'deleteGroup', 'getGroups', 'addToGroup', 'removeFromGroup', 'canCreateUser', 'canCreateGroup']):
            raise ValueError("must be one of enum values ('createUser', 'getUsers', 'setUser', 'disable', 'deleteUser', 'enable', 'changePassword', 'getKeys', 'addKey', 'deleteKey', 'createGroup', 'deleteGroup', 'getGroups', 'addToGroup', 'removeFromGroup', 'canCreateUser', 'canCreateGroup')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Users from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of group
        if self.group:
            _dict['group'] = self.group.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Users from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operation": obj.get("operation"),
            "create_group": obj.get("create_group"),
            "new_password": obj.get("new_password"),
            "old_password": obj.get("old_password"),
            "group_name": obj.get("group_name"),
            "replace_primary_group": obj.get("replace_primary_group"),
            "with_tags": obj.get("with_tags"),
            "user": UsersUser.from_dict(obj["user"]) if obj.get("user") is not None else None,
            "group": UsersGroup.from_dict(obj["group"]) if obj.get("group") is not None else None
        })
        return _obj


