# coding: utf-8

"""
    Severalnines ClusterControl REST API (V2)

    REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.  # noqa: E501

    The version of the OpenAPI document: OpenAPI specification v1.0.0
    Contact: sales@severalnines.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_cc_client.configuration import Configuration


class Backup(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'operation': 'str',
        'cluster_id': 'int',
        'ascending': 'bool',
        'schedule': 'BackupSchedule',
        'backup_record': 'BackupBackupRecord'
    }

    attribute_map = {
        'operation': 'operation',
        'cluster_id': 'cluster_id',
        'ascending': 'ascending',
        'schedule': 'schedule',
        'backup_record': 'backup_record'
    }

    def __init__(self, operation=None, cluster_id=None, ascending=None, schedule=None, backup_record=None, local_vars_configuration=None):  # noqa: E501
        """Backup - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._operation = None
        self._cluster_id = None
        self._ascending = None
        self._schedule = None
        self._backup_record = None
        self.discriminator = None

        self.operation = operation
        if cluster_id is not None:
            self.cluster_id = cluster_id
        if ascending is not None:
            self.ascending = ascending
        if schedule is not None:
            self.schedule = schedule
        if backup_record is not None:
            self.backup_record = backup_record

    @property
    def operation(self):
        """Gets the operation of this Backup.  # noqa: E501


        :return: The operation of this Backup.  # noqa: E501
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this Backup.


        :param operation: The operation of this Backup.  # noqa: E501
        :type operation: str
        """
        if self.local_vars_configuration.client_side_validation and operation is None:  # noqa: E501
            raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501
        allowed_values = ["getBackups", "getBackupSchedules", "scheduleBackup", "deleteBackupRecord"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and operation not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `operation` ({0}), must be one of {1}"  # noqa: E501
                .format(operation, allowed_values)
            )

        self._operation = operation

    @property
    def cluster_id(self):
        """Gets the cluster_id of this Backup.  # noqa: E501


        :return: The cluster_id of this Backup.  # noqa: E501
        :rtype: int
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """Sets the cluster_id of this Backup.


        :param cluster_id: The cluster_id of this Backup.  # noqa: E501
        :type cluster_id: int
        """

        self._cluster_id = cluster_id

    @property
    def ascending(self):
        """Gets the ascending of this Backup.  # noqa: E501


        :return: The ascending of this Backup.  # noqa: E501
        :rtype: bool
        """
        return self._ascending

    @ascending.setter
    def ascending(self, ascending):
        """Sets the ascending of this Backup.


        :param ascending: The ascending of this Backup.  # noqa: E501
        :type ascending: bool
        """

        self._ascending = ascending

    @property
    def schedule(self):
        """Gets the schedule of this Backup.  # noqa: E501


        :return: The schedule of this Backup.  # noqa: E501
        :rtype: BackupSchedule
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule):
        """Sets the schedule of this Backup.


        :param schedule: The schedule of this Backup.  # noqa: E501
        :type schedule: BackupSchedule
        """

        self._schedule = schedule

    @property
    def backup_record(self):
        """Gets the backup_record of this Backup.  # noqa: E501


        :return: The backup_record of this Backup.  # noqa: E501
        :rtype: BackupBackupRecord
        """
        return self._backup_record

    @backup_record.setter
    def backup_record(self, backup_record):
        """Sets the backup_record of this Backup.


        :param backup_record: The backup_record of this Backup.  # noqa: E501
        :type backup_record: BackupBackupRecord
        """

        self._backup_record = backup_record

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Backup):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Backup):
            return True

        return self.to_dict() != other.to_dict()
