# coding: utf-8

"""
    Severalnines ClusterControl REST API (V2)

    REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

    The version of the OpenAPI document: OpenAPI specification v1.0.0
    Contact: sales@severalnines.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, validator
from openapi_cc_client.models.cloud_credentials import CloudCredentials

class Cloud(BaseModel):
    """
    Cloud
    """
    operation: StrictStr = Field(...)
    provider: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    comment: Optional[StrictStr] = None
    id: Optional[StrictInt] = None
    credentials: Optional[CloudCredentials] = None
    __properties = ["operation", "provider", "name", "comment", "id", "credentials"]

    @validator('operation')
    def operation_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('verifyCredentials', 'listCredentials', 'getCredentials', 'addCredentials', 'updateCredentials', 'removeCredentials'):
            raise ValueError("must be one of enum values ('verifyCredentials', 'listCredentials', 'getCredentials', 'addCredentials', 'updateCredentials', 'removeCredentials')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Cloud:
        """Create an instance of Cloud from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of credentials
        if self.credentials:
            _dict['credentials'] = self.credentials.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Cloud:
        """Create an instance of Cloud from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Cloud.parse_obj(obj)

        _obj = Cloud.parse_obj({
            "operation": obj.get("operation"),
            "provider": obj.get("provider"),
            "name": obj.get("name"),
            "comment": obj.get("comment"),
            "id": obj.get("id"),
            "credentials": CloudCredentials.from_dict(obj.get("credentials")) if obj.get("credentials") is not None else None
        })
        return _obj


