# coding: utf-8

"""
    Severalnines ClusterControl REST API (V2)

    REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

    The version of the OpenAPI document: OpenAPI specification v1.0.0
    Contact: sales@severalnines.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt, StrictStr

class HostHost(BaseModel):
    """
    HostHost
    """
    class_name: Optional[StrictStr] = None
    hostname: Optional[StrictStr] = None
    port: Optional[StrictInt] = None
    __properties = ["class_name", "hostname", "port"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> HostHost:
        """Create an instance of HostHost from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> HostHost:
        """Create an instance of HostHost from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return HostHost.parse_obj(obj)

        _obj = HostHost.parse_obj({
            "class_name": obj.get("class_name"),
            "hostname": obj.get("hostname"),
            "port": obj.get("port")
        })
        return _obj


