# coding: utf-8

"""
    Severalnines ClusterControl REST API (V2)

    REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

    The version of the OpenAPI document: OpenAPI specification v1.0.0
    Contact: sales@severalnines.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, StrictStr, conlist
from openapi_cc_client.models.jobs_job_job_spec_job_data_replica_sets_inner_members_inner import JobsJobJobSpecJobDataReplicaSetsInnerMembersInner

class JobsJobJobSpecJobDataReplicaSetsInner(BaseModel):
    """
    JobsJobJobSpecJobDataReplicaSetsInner
    """
    rs: Optional[StrictStr] = None
    members: Optional[conlist(JobsJobJobSpecJobDataReplicaSetsInnerMembersInner)] = None
    __properties = ["rs", "members"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> JobsJobJobSpecJobDataReplicaSetsInner:
        """Create an instance of JobsJobJobSpecJobDataReplicaSetsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in members (list)
        _items = []
        if self.members:
            for _item in self.members:
                if _item:
                    _items.append(_item.to_dict())
            _dict['members'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> JobsJobJobSpecJobDataReplicaSetsInner:
        """Create an instance of JobsJobJobSpecJobDataReplicaSetsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return JobsJobJobSpecJobDataReplicaSetsInner.parse_obj(obj)

        _obj = JobsJobJobSpecJobDataReplicaSetsInner.parse_obj({
            "rs": obj.get("rs"),
            "members": [JobsJobJobSpecJobDataReplicaSetsInnerMembersInner.from_dict(_item) for _item in obj.get("members")] if obj.get("members") is not None else None
        })
        return _obj


