# coding: utf-8

"""
    Severalnines ClusterControl REST API (V2)

    REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.  # noqa: E501

    The version of the OpenAPI document: OpenAPI specification v1.0.0
    Contact: sales@severalnines.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_cc_client.configuration import Configuration


class JobsJobJobSpecJobDataNodeConfigurationInner(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'arguments': 'str',
        'job': 'str',
        'scrape_interval': 'str'
    }

    attribute_map = {
        'arguments': 'arguments',
        'job': 'job',
        'scrape_interval': 'scrape_interval'
    }

    def __init__(self, arguments=None, job=None, scrape_interval=None, local_vars_configuration=None):  # noqa: E501
        """JobsJobJobSpecJobDataNodeConfigurationInner - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._arguments = None
        self._job = None
        self._scrape_interval = None
        self.discriminator = None

        if arguments is not None:
            self.arguments = arguments
        if job is not None:
            self.job = job
        if scrape_interval is not None:
            self.scrape_interval = scrape_interval

    @property
    def arguments(self):
        """Gets the arguments of this JobsJobJobSpecJobDataNodeConfigurationInner.  # noqa: E501


        :return: The arguments of this JobsJobJobSpecJobDataNodeConfigurationInner.  # noqa: E501
        :rtype: str
        """
        return self._arguments

    @arguments.setter
    def arguments(self, arguments):
        """Sets the arguments of this JobsJobJobSpecJobDataNodeConfigurationInner.


        :param arguments: The arguments of this JobsJobJobSpecJobDataNodeConfigurationInner.  # noqa: E501
        :type arguments: str
        """

        self._arguments = arguments

    @property
    def job(self):
        """Gets the job of this JobsJobJobSpecJobDataNodeConfigurationInner.  # noqa: E501


        :return: The job of this JobsJobJobSpecJobDataNodeConfigurationInner.  # noqa: E501
        :rtype: str
        """
        return self._job

    @job.setter
    def job(self, job):
        """Sets the job of this JobsJobJobSpecJobDataNodeConfigurationInner.


        :param job: The job of this JobsJobJobSpecJobDataNodeConfigurationInner.  # noqa: E501
        :type job: str
        """
        allowed_values = ["node", "mysqld", "mongo"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and job not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `job` ({0}), must be one of {1}"  # noqa: E501
                .format(job, allowed_values)
            )

        self._job = job

    @property
    def scrape_interval(self):
        """Gets the scrape_interval of this JobsJobJobSpecJobDataNodeConfigurationInner.  # noqa: E501


        :return: The scrape_interval of this JobsJobJobSpecJobDataNodeConfigurationInner.  # noqa: E501
        :rtype: str
        """
        return self._scrape_interval

    @scrape_interval.setter
    def scrape_interval(self, scrape_interval):
        """Sets the scrape_interval of this JobsJobJobSpecJobDataNodeConfigurationInner.


        :param scrape_interval: The scrape_interval of this JobsJobJobSpecJobDataNodeConfigurationInner.  # noqa: E501
        :type scrape_interval: str
        """

        self._scrape_interval = scrape_interval

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobsJobJobSpecJobDataNodeConfigurationInner):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, JobsJobJobSpecJobDataNodeConfigurationInner):
            return True

        return self.to_dict() != other.to_dict()
