# coding: utf-8

"""
    Severalnines ClusterControl REST API (V2)

    REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.  # noqa: E501

    The version of the OpenAPI document: OpenAPI specification v1.0.0
    Contact: sales@severalnines.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_cc_client.configuration import Configuration


class StatCmonAgentRequestData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'begin': 'str',
        'class_name': 'str',
        'end': 'str',
        'limit': 'int',
        'mime_type': 'str',
        'object_name': 'str',
        'origin': 'str'
    }

    attribute_map = {
        'begin': 'begin',
        'class_name': 'className',
        'end': 'end',
        'limit': 'limit',
        'mime_type': 'mimeType',
        'object_name': 'objectName',
        'origin': 'origin'
    }

    def __init__(self, begin=None, class_name=None, end=None, limit=None, mime_type=None, object_name=None, origin=None, local_vars_configuration=None):  # noqa: E501
        """StatCmonAgentRequestData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._begin = None
        self._class_name = None
        self._end = None
        self._limit = None
        self._mime_type = None
        self._object_name = None
        self._origin = None
        self.discriminator = None

        if begin is not None:
            self.begin = begin
        if class_name is not None:
            self.class_name = class_name
        if end is not None:
            self.end = end
        if limit is not None:
            self.limit = limit
        if mime_type is not None:
            self.mime_type = mime_type
        if object_name is not None:
            self.object_name = object_name
        if origin is not None:
            self.origin = origin

    @property
    def begin(self):
        """Gets the begin of this StatCmonAgentRequestData.  # noqa: E501

        e.g. \"2021-06-07T09:41:43.636Z\"  # noqa: E501

        :return: The begin of this StatCmonAgentRequestData.  # noqa: E501
        :rtype: str
        """
        return self._begin

    @begin.setter
    def begin(self, begin):
        """Sets the begin of this StatCmonAgentRequestData.

        e.g. \"2021-06-07T09:41:43.636Z\"  # noqa: E501

        :param begin: The begin of this StatCmonAgentRequestData.  # noqa: E501
        :type begin: str
        """

        self._begin = begin

    @property
    def class_name(self):
        """Gets the class_name of this StatCmonAgentRequestData.  # noqa: E501


        :return: The class_name of this StatCmonAgentRequestData.  # noqa: E501
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name):
        """Sets the class_name of this StatCmonAgentRequestData.


        :param class_name: The class_name of this StatCmonAgentRequestData.  # noqa: E501
        :type class_name: str
        """
        allowed_values = ["CmnReadParam"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and class_name not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `class_name` ({0}), must be one of {1}"  # noqa: E501
                .format(class_name, allowed_values)
            )

        self._class_name = class_name

    @property
    def end(self):
        """Gets the end of this StatCmonAgentRequestData.  # noqa: E501

        e.g. \"2021-06-07T09:41:43.636Z\"  # noqa: E501

        :return: The end of this StatCmonAgentRequestData.  # noqa: E501
        :rtype: str
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this StatCmonAgentRequestData.

        e.g. \"2021-06-07T09:41:43.636Z\"  # noqa: E501

        :param end: The end of this StatCmonAgentRequestData.  # noqa: E501
        :type end: str
        """

        self._end = end

    @property
    def limit(self):
        """Gets the limit of this StatCmonAgentRequestData.  # noqa: E501


        :return: The limit of this StatCmonAgentRequestData.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this StatCmonAgentRequestData.


        :param limit: The limit of this StatCmonAgentRequestData.  # noqa: E501
        :type limit: int
        """

        self._limit = limit

    @property
    def mime_type(self):
        """Gets the mime_type of this StatCmonAgentRequestData.  # noqa: E501


        :return: The mime_type of this StatCmonAgentRequestData.  # noqa: E501
        :rtype: str
        """
        return self._mime_type

    @mime_type.setter
    def mime_type(self, mime_type):
        """Sets the mime_type of this StatCmonAgentRequestData.


        :param mime_type: The mime_type of this StatCmonAgentRequestData.  # noqa: E501
        :type mime_type: str
        """

        self._mime_type = mime_type

    @property
    def object_name(self):
        """Gets the object_name of this StatCmonAgentRequestData.  # noqa: E501


        :return: The object_name of this StatCmonAgentRequestData.  # noqa: E501
        :rtype: str
        """
        return self._object_name

    @object_name.setter
    def object_name(self, object_name):
        """Sets the object_name of this StatCmonAgentRequestData.


        :param object_name: The object_name of this StatCmonAgentRequestData.  # noqa: E501
        :type object_name: str
        """

        self._object_name = object_name

    @property
    def origin(self):
        """Gets the origin of this StatCmonAgentRequestData.  # noqa: E501


        :return: The origin of this StatCmonAgentRequestData.  # noqa: E501
        :rtype: str
        """
        return self._origin

    @origin.setter
    def origin(self, origin):
        """Sets the origin of this StatCmonAgentRequestData.


        :param origin: The origin of this StatCmonAgentRequestData.  # noqa: E501
        :type origin: str
        """
        allowed_values = ["timeline"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and origin not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `origin` ({0}), must be one of {1}"  # noqa: E501
                .format(origin, allowed_values)
            )

        self._origin = origin

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StatCmonAgentRequestData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StatCmonAgentRequestData):
            return True

        return self.to_dict() != other.to_dict()
