# coding: utf-8

"""
    Severalnines ClusterControl REST API (V2)

    REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.  # noqa: E501

    The version of the OpenAPI document: OpenAPI specification v1.0.0
    Contact: sales@severalnines.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_cc_client.configuration import Configuration


class UsersUserGroupsInner(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'class_name': 'str',
        'group_name': 'str',
        'group_id': 'int'
    }

    attribute_map = {
        'class_name': 'class_name',
        'group_name': 'group_name',
        'group_id': 'group_id'
    }

    def __init__(self, class_name=None, group_name=None, group_id=None, local_vars_configuration=None):  # noqa: E501
        """UsersUserGroupsInner - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._class_name = None
        self._group_name = None
        self._group_id = None
        self.discriminator = None

        if class_name is not None:
            self.class_name = class_name
        if group_name is not None:
            self.group_name = group_name
        if group_id is not None:
            self.group_id = group_id

    @property
    def class_name(self):
        """Gets the class_name of this UsersUserGroupsInner.  # noqa: E501


        :return: The class_name of this UsersUserGroupsInner.  # noqa: E501
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name):
        """Sets the class_name of this UsersUserGroupsInner.


        :param class_name: The class_name of this UsersUserGroupsInner.  # noqa: E501
        :type class_name: str
        """

        self._class_name = class_name

    @property
    def group_name(self):
        """Gets the group_name of this UsersUserGroupsInner.  # noqa: E501


        :return: The group_name of this UsersUserGroupsInner.  # noqa: E501
        :rtype: str
        """
        return self._group_name

    @group_name.setter
    def group_name(self, group_name):
        """Sets the group_name of this UsersUserGroupsInner.


        :param group_name: The group_name of this UsersUserGroupsInner.  # noqa: E501
        :type group_name: str
        """

        self._group_name = group_name

    @property
    def group_id(self):
        """Gets the group_id of this UsersUserGroupsInner.  # noqa: E501


        :return: The group_id of this UsersUserGroupsInner.  # noqa: E501
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this UsersUserGroupsInner.


        :param group_id: The group_id of this UsersUserGroupsInner.  # noqa: E501
        :type group_id: int
        """

        self._group_id = group_id

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UsersUserGroupsInner):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UsersUserGroupsInner):
            return True

        return self.to_dict() != other.to_dict()
