# coding: utf-8

"""
    Severalnines ClusterControl Proxy - REST API

    REST API specification for ClusterControl Proxy. The Proxy is the foundation for Controller of Controllers, (a.k.a. multi-controllers).

    The version of the OpenAPI document: OpenAPI specification v1.0.0
    Contact: sales@severalnines.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_proxy_client.models.authenticate_response import AuthenticateResponse

class TestAuthenticateResponse(unittest.TestCase):
    """AuthenticateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthenticateResponse:
        """Test AuthenticateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthenticateResponse`
        """
        model = AuthenticateResponse()
        if include_optional:
            return AuthenticateResponse(
                request_created = '',
                request_processed = '',
                request_status = '',
                user = openapi_proxy_client.models.authenticate_response_user.AuthenticateResponse_user(
                    username = '', 
                    email = '', 
                    firstname = '', 
                    lastname = '', 
                    cmon = True, 
                    groups = [
                        ''
                        ], )
            )
        else:
            return AuthenticateResponse(
        )
        """

    def testAuthenticateResponse(self):
        """Test AuthenticateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
