/*
 * Severalnines ClusterControl
 * This is a ...
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sales@severalnines.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.ccapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.ccapi.client.model.BackupBackupRecord;
import org.openapitools.ccapi.client.model.BackupSchedule;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Backup
 */
public class BackupTest {
    private final Backup model = new Backup();

    /**
     * Model tests for Backup
     */
    @Test
    public void testBackup() {
        // TODO: test Backup
    }

    /**
     * Test the property 'operation'
     */
    @Test
    public void operationTest() {
        // TODO: test operation
    }

    /**
     * Test the property 'clusterId'
     */
    @Test
    public void clusterIdTest() {
        // TODO: test clusterId
    }

    /**
     * Test the property 'ascending'
     */
    @Test
    public void ascendingTest() {
        // TODO: test ascending
    }

    /**
     * Test the property 'schedule'
     */
    @Test
    public void scheduleTest() {
        // TODO: test schedule
    }

    /**
     * Test the property 'backupRecord'
     */
    @Test
    public void backupRecordTest() {
        // TODO: test backupRecord
    }

}
