/*
 * Severalnines ClusterControl
 * This is a ...
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sales@severalnines.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.ccapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobsJobJobSpecJobDataNodesInner
 */
public class JobsJobJobSpecJobDataNodesInnerTest {
    private final JobsJobJobSpecJobDataNodesInner model = new JobsJobJobSpecJobDataNodesInner();

    /**
     * Model tests for JobsJobJobSpecJobDataNodesInner
     */
    @Test
    public void testJobsJobJobSpecJobDataNodesInner() {
        // TODO: test JobsJobJobSpecJobDataNodesInner
    }

    /**
     * Test the property 'className'
     */
    @Test
    public void classNameTest() {
        // TODO: test className
    }

    /**
     * Test the property 'cdtPath'
     */
    @Test
    public void cdtPathTest() {
        // TODO: test cdtPath
    }

    /**
     * Test the property 'acl'
     */
    @Test
    public void aclTest() {
        // TODO: test acl
    }

    /**
     * Test the property 'clusterid'
     */
    @Test
    public void clusteridTest() {
        // TODO: test clusterid
    }

    /**
     * Test the property 'ip'
     */
    @Test
    public void ipTest() {
        // TODO: test ip
    }

    /**
     * Test the property 'maintenanceMode'
     */
    @Test
    public void maintenanceModeTest() {
        // TODO: test maintenanceMode
    }

    /**
     * Test the property 'maintenanceModeActive'
     */
    @Test
    public void maintenanceModeActiveTest() {
        // TODO: test maintenanceModeActive
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'uniqueId'
     */
    @Test
    public void uniqueIdTest() {
        // TODO: test uniqueId
    }

    /**
     * Test the property 'hostname'
     */
    @Test
    public void hostnameTest() {
        // TODO: test hostname
    }

    /**
     * Test the property 'hostnameData'
     */
    @Test
    public void hostnameDataTest() {
        // TODO: test hostnameData
    }

    /**
     * Test the property 'hostnameInternal'
     */
    @Test
    public void hostnameInternalTest() {
        // TODO: test hostnameInternal
    }

    /**
     * Test the property 'port'
     */
    @Test
    public void portTest() {
        // TODO: test port
    }

    /**
     * Test the property 'nodetype'
     */
    @Test
    public void nodetypeTest() {
        // TODO: test nodetype
    }

    /**
     * Test the property 'configfile'
     */
    @Test
    public void configfileTest() {
        // TODO: test configfile
    }

    /**
     * Test the property 'datadir'
     */
    @Test
    public void datadirTest() {
        // TODO: test datadir
    }

    /**
     * Test the property 'backupDir'
     */
    @Test
    public void backupDirTest() {
        // TODO: test backupDir
    }

    /**
     * Test the property 'synchronous'
     */
    @Test
    public void synchronousTest() {
        // TODO: test synchronous
    }

}
