/*
 * Severalnines ClusterControl
 * This is a ...
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sales@severalnines.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.ccapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Stat
 */
public class StatTest {
    private final Stat model = new Stat();

    /**
     * Model tests for Stat
     */
    @Test
    public void testStat() {
        // TODO: test Stat
    }

    /**
     * Test the property 'operation'
     */
    @Test
    public void operationTest() {
        // TODO: test operation
    }

    /**
     * Test the property 'clusterId'
     */
    @Test
    public void clusterIdTest() {
        // TODO: test clusterId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'startDatetime'
     */
    @Test
    public void startDatetimeTest() {
        // TODO: test startDatetime
    }

    /**
     * Test the property 'endDatetime'
     */
    @Test
    public void endDatetimeTest() {
        // TODO: test endDatetime
    }

    /**
     * Test the property 'withHosts'
     */
    @Test
    public void withHostsTest() {
        // TODO: test withHosts
    }

    /**
     * Test the property 'calculatePerSec'
     */
    @Test
    public void calculatePerSecTest() {
        // TODO: test calculatePerSec
    }

}
