/*
 * Severalnines ClusterControl
 * This is a ...
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sales@severalnines.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.ccapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StatCmonAgentRequestData
 */
public class StatCmonAgentRequestDataTest {
    private final StatCmonAgentRequestData model = new StatCmonAgentRequestData();

    /**
     * Model tests for StatCmonAgentRequestData
     */
    @Test
    public void testStatCmonAgentRequestData() {
        // TODO: test StatCmonAgentRequestData
    }

    /**
     * Test the property 'begin'
     */
    @Test
    public void beginTest() {
        // TODO: test begin
    }

    /**
     * Test the property 'className'
     */
    @Test
    public void classNameTest() {
        // TODO: test className
    }

    /**
     * Test the property 'end'
     */
    @Test
    public void endTest() {
        // TODO: test end
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'mimeType'
     */
    @Test
    public void mimeTypeTest() {
        // TODO: test mimeType
    }

    /**
     * Test the property 'objectName'
     */
    @Test
    public void objectNameTest() {
        // TODO: test objectName
    }

    /**
     * Test the property 'origin'
     */
    @Test
    public void originTest() {
        // TODO: test origin
    }

}
