# coding: utf-8

"""
    Severalnines ClusterControl REST API (V2)

    REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

    The version of the OpenAPI document: OpenAPI specification v1.0.0
    Contact: sales@severalnines.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_cc_client.models.cluster_response_hosts_inner import ClusterResponseHostsInner

class TestClusterResponseHostsInner(unittest.TestCase):
    """ClusterResponseHostsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterResponseHostsInner:
        """Test ClusterResponseHostsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterResponseHostsInner`
        """
        model = ClusterResponseHostsInner()
        if include_optional:
            return ClusterResponseHostsInner(
                class_name = '',
                hostid = 56,
                datadir = '',
                hostname = '',
                hostname_data = '',
                hostname_internal = '',
                role = '',
                synchronous = True,
                member_role = '',
                roleid = 56,
                rs = '',
                version = '',
                elastic_roles = ''
            )
        else:
            return ClusterResponseHostsInner(
        )
        """

    def testClusterResponseHostsInner(self):
        """Test ClusterResponseHostsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
