/*
Severalnines ClusterControl REST API (V2)

REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

API version: OpenAPI specification v1.0.0
Contact: sales@severalnines.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DiscoveryJob Also ckeck the passed create_cluster job
type DiscoveryJob struct {
	ClassName *string `json:"class_name,omitempty"`
	JobSpec *DiscoveryJobJobSpec `json:"job_spec,omitempty"`
}

// NewDiscoveryJob instantiates a new DiscoveryJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiscoveryJob() *DiscoveryJob {
	this := DiscoveryJob{}
	return &this
}

// NewDiscoveryJobWithDefaults instantiates a new DiscoveryJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiscoveryJobWithDefaults() *DiscoveryJob {
	this := DiscoveryJob{}
	return &this
}

// GetClassName returns the ClassName field value if set, zero value otherwise.
func (o *DiscoveryJob) GetClassName() string {
	if o == nil || isNil(o.ClassName) {
		var ret string
		return ret
	}
	return *o.ClassName
}

// GetClassNameOk returns a tuple with the ClassName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscoveryJob) GetClassNameOk() (*string, bool) {
	if o == nil || isNil(o.ClassName) {
    return nil, false
	}
	return o.ClassName, true
}

// HasClassName returns a boolean if a field has been set.
func (o *DiscoveryJob) HasClassName() bool {
	if o != nil && !isNil(o.ClassName) {
		return true
	}

	return false
}

// SetClassName gets a reference to the given string and assigns it to the ClassName field.
func (o *DiscoveryJob) SetClassName(v string) {
	o.ClassName = &v
}

// GetJobSpec returns the JobSpec field value if set, zero value otherwise.
func (o *DiscoveryJob) GetJobSpec() DiscoveryJobJobSpec {
	if o == nil || isNil(o.JobSpec) {
		var ret DiscoveryJobJobSpec
		return ret
	}
	return *o.JobSpec
}

// GetJobSpecOk returns a tuple with the JobSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscoveryJob) GetJobSpecOk() (*DiscoveryJobJobSpec, bool) {
	if o == nil || isNil(o.JobSpec) {
    return nil, false
	}
	return o.JobSpec, true
}

// HasJobSpec returns a boolean if a field has been set.
func (o *DiscoveryJob) HasJobSpec() bool {
	if o != nil && !isNil(o.JobSpec) {
		return true
	}

	return false
}

// SetJobSpec gets a reference to the given DiscoveryJobJobSpec and assigns it to the JobSpec field.
func (o *DiscoveryJob) SetJobSpec(v DiscoveryJobJobSpec) {
	o.JobSpec = &v
}

func (o DiscoveryJob) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ClassName) {
		toSerialize["class_name"] = o.ClassName
	}
	if !isNil(o.JobSpec) {
		toSerialize["job_spec"] = o.JobSpec
	}
	return json.Marshal(toSerialize)
}

type NullableDiscoveryJob struct {
	value *DiscoveryJob
	isSet bool
}

func (v NullableDiscoveryJob) Get() *DiscoveryJob {
	return v.value
}

func (v *NullableDiscoveryJob) Set(val *DiscoveryJob) {
	v.value = val
	v.isSet = true
}

func (v NullableDiscoveryJob) IsSet() bool {
	return v.isSet
}

func (v *NullableDiscoveryJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiscoveryJob(val *DiscoveryJob) *NullableDiscoveryJob {
	return &NullableDiscoveryJob{value: val, isSet: true}
}

func (v NullableDiscoveryJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiscoveryJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


