/*
Severalnines ClusterControl REST API (V2)

REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

API version: OpenAPI specification v1.0.0
Contact: sales@severalnines.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the JobsJobJobSpecJobDataTopology type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobsJobJobSpecJobDataTopology{}

// JobsJobJobSpecJobDataTopology struct for JobsJobJobSpecJobDataTopology
type JobsJobJobSpecJobDataTopology struct {
	MasterSlaveLinks []map[string]string `json:"master_slave_links,omitempty"`
}

// NewJobsJobJobSpecJobDataTopology instantiates a new JobsJobJobSpecJobDataTopology object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobsJobJobSpecJobDataTopology() *JobsJobJobSpecJobDataTopology {
	this := JobsJobJobSpecJobDataTopology{}
	return &this
}

// NewJobsJobJobSpecJobDataTopologyWithDefaults instantiates a new JobsJobJobSpecJobDataTopology object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobsJobJobSpecJobDataTopologyWithDefaults() *JobsJobJobSpecJobDataTopology {
	this := JobsJobJobSpecJobDataTopology{}
	return &this
}

// GetMasterSlaveLinks returns the MasterSlaveLinks field value if set, zero value otherwise.
func (o *JobsJobJobSpecJobDataTopology) GetMasterSlaveLinks() []map[string]string {
	if o == nil || IsNil(o.MasterSlaveLinks) {
		var ret []map[string]string
		return ret
	}
	return o.MasterSlaveLinks
}

// GetMasterSlaveLinksOk returns a tuple with the MasterSlaveLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsJobJobSpecJobDataTopology) GetMasterSlaveLinksOk() ([]map[string]string, bool) {
	if o == nil || IsNil(o.MasterSlaveLinks) {
		return nil, false
	}
	return o.MasterSlaveLinks, true
}

// HasMasterSlaveLinks returns a boolean if a field has been set.
func (o *JobsJobJobSpecJobDataTopology) HasMasterSlaveLinks() bool {
	if o != nil && !IsNil(o.MasterSlaveLinks) {
		return true
	}

	return false
}

// SetMasterSlaveLinks gets a reference to the given []map[string]string and assigns it to the MasterSlaveLinks field.
func (o *JobsJobJobSpecJobDataTopology) SetMasterSlaveLinks(v []map[string]string) {
	o.MasterSlaveLinks = v
}

func (o JobsJobJobSpecJobDataTopology) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobsJobJobSpecJobDataTopology) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MasterSlaveLinks) {
		toSerialize["master_slave_links"] = o.MasterSlaveLinks
	}
	return toSerialize, nil
}

type NullableJobsJobJobSpecJobDataTopology struct {
	value *JobsJobJobSpecJobDataTopology
	isSet bool
}

func (v NullableJobsJobJobSpecJobDataTopology) Get() *JobsJobJobSpecJobDataTopology {
	return v.value
}

func (v *NullableJobsJobJobSpecJobDataTopology) Set(val *JobsJobJobSpecJobDataTopology) {
	v.value = val
	v.isSet = true
}

func (v NullableJobsJobJobSpecJobDataTopology) IsSet() bool {
	return v.isSet
}

func (v *NullableJobsJobJobSpecJobDataTopology) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobsJobJobSpecJobDataTopology(val *JobsJobJobSpecJobDataTopology) *NullableJobsJobJobSpecJobDataTopology {
	return &NullableJobsJobJobSpecJobDataTopology{value: val, isSet: true}
}

func (v NullableJobsJobJobSpecJobDataTopology) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobsJobJobSpecJobDataTopology) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


