/*
Severalnines ClusterControl

This is a ...

API version: 1.0.0
Contact: sales@severalnines.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ClustersConfigurationInner struct for ClustersConfigurationInner
type ClustersConfigurationInner struct {
	Name *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewClustersConfigurationInner instantiates a new ClustersConfigurationInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClustersConfigurationInner() *ClustersConfigurationInner {
	this := ClustersConfigurationInner{}
	return &this
}

// NewClustersConfigurationInnerWithDefaults instantiates a new ClustersConfigurationInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClustersConfigurationInnerWithDefaults() *ClustersConfigurationInner {
	this := ClustersConfigurationInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ClustersConfigurationInner) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersConfigurationInner) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ClustersConfigurationInner) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ClustersConfigurationInner) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ClustersConfigurationInner) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersConfigurationInner) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ClustersConfigurationInner) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ClustersConfigurationInner) SetValue(v string) {
	o.Value = &v
}

func (o ClustersConfigurationInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableClustersConfigurationInner struct {
	value *ClustersConfigurationInner
	isSet bool
}

func (v NullableClustersConfigurationInner) Get() *ClustersConfigurationInner {
	return v.value
}

func (v *NullableClustersConfigurationInner) Set(val *ClustersConfigurationInner) {
	v.value = val
	v.isSet = true
}

func (v NullableClustersConfigurationInner) IsSet() bool {
	return v.isSet
}

func (v *NullableClustersConfigurationInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClustersConfigurationInner(val *ClustersConfigurationInner) *NullableClustersConfigurationInner {
	return &NullableClustersConfigurationInner{value: val, isSet: true}
}

func (v NullableClustersConfigurationInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClustersConfigurationInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


