/*
Severalnines ClusterControl REST API (V2)

REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

API version: OpenAPI specification v1.0.0
Contact: sales@severalnines.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// JobsJobJobSpecJobDataConfigServersMembersInner struct for JobsJobJobSpecJobDataConfigServersMembersInner
type JobsJobJobSpecJobDataConfigServersMembersInner struct {
	Hostname *string `json:"hostname,omitempty"`
	HostnameData *string `json:"hostname_data,omitempty"`
	HostnameInternal *string `json:"hostname_internal,omitempty"`
	Port *string `json:"port,omitempty"`
}

// NewJobsJobJobSpecJobDataConfigServersMembersInner instantiates a new JobsJobJobSpecJobDataConfigServersMembersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobsJobJobSpecJobDataConfigServersMembersInner() *JobsJobJobSpecJobDataConfigServersMembersInner {
	this := JobsJobJobSpecJobDataConfigServersMembersInner{}
	return &this
}

// NewJobsJobJobSpecJobDataConfigServersMembersInnerWithDefaults instantiates a new JobsJobJobSpecJobDataConfigServersMembersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobsJobJobSpecJobDataConfigServersMembersInnerWithDefaults() *JobsJobJobSpecJobDataConfigServersMembersInner {
	this := JobsJobJobSpecJobDataConfigServersMembersInner{}
	return &this
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) GetHostname() string {
	if o == nil || isNil(o.Hostname) {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) GetHostnameOk() (*string, bool) {
	if o == nil || isNil(o.Hostname) {
    return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) HasHostname() bool {
	if o != nil && !isNil(o.Hostname) {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) SetHostname(v string) {
	o.Hostname = &v
}

// GetHostnameData returns the HostnameData field value if set, zero value otherwise.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) GetHostnameData() string {
	if o == nil || isNil(o.HostnameData) {
		var ret string
		return ret
	}
	return *o.HostnameData
}

// GetHostnameDataOk returns a tuple with the HostnameData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) GetHostnameDataOk() (*string, bool) {
	if o == nil || isNil(o.HostnameData) {
    return nil, false
	}
	return o.HostnameData, true
}

// HasHostnameData returns a boolean if a field has been set.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) HasHostnameData() bool {
	if o != nil && !isNil(o.HostnameData) {
		return true
	}

	return false
}

// SetHostnameData gets a reference to the given string and assigns it to the HostnameData field.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) SetHostnameData(v string) {
	o.HostnameData = &v
}

// GetHostnameInternal returns the HostnameInternal field value if set, zero value otherwise.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) GetHostnameInternal() string {
	if o == nil || isNil(o.HostnameInternal) {
		var ret string
		return ret
	}
	return *o.HostnameInternal
}

// GetHostnameInternalOk returns a tuple with the HostnameInternal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) GetHostnameInternalOk() (*string, bool) {
	if o == nil || isNil(o.HostnameInternal) {
    return nil, false
	}
	return o.HostnameInternal, true
}

// HasHostnameInternal returns a boolean if a field has been set.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) HasHostnameInternal() bool {
	if o != nil && !isNil(o.HostnameInternal) {
		return true
	}

	return false
}

// SetHostnameInternal gets a reference to the given string and assigns it to the HostnameInternal field.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) SetHostnameInternal(v string) {
	o.HostnameInternal = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) GetPort() string {
	if o == nil || isNil(o.Port) {
		var ret string
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) GetPortOk() (*string, bool) {
	if o == nil || isNil(o.Port) {
    return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) HasPort() bool {
	if o != nil && !isNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given string and assigns it to the Port field.
func (o *JobsJobJobSpecJobDataConfigServersMembersInner) SetPort(v string) {
	o.Port = &v
}

func (o JobsJobJobSpecJobDataConfigServersMembersInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Hostname) {
		toSerialize["hostname"] = o.Hostname
	}
	if !isNil(o.HostnameData) {
		toSerialize["hostname_data"] = o.HostnameData
	}
	if !isNil(o.HostnameInternal) {
		toSerialize["hostname_internal"] = o.HostnameInternal
	}
	if !isNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	return json.Marshal(toSerialize)
}

type NullableJobsJobJobSpecJobDataConfigServersMembersInner struct {
	value *JobsJobJobSpecJobDataConfigServersMembersInner
	isSet bool
}

func (v NullableJobsJobJobSpecJobDataConfigServersMembersInner) Get() *JobsJobJobSpecJobDataConfigServersMembersInner {
	return v.value
}

func (v *NullableJobsJobJobSpecJobDataConfigServersMembersInner) Set(val *JobsJobJobSpecJobDataConfigServersMembersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableJobsJobJobSpecJobDataConfigServersMembersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableJobsJobJobSpecJobDataConfigServersMembersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobsJobJobSpecJobDataConfigServersMembersInner(val *JobsJobJobSpecJobDataConfigServersMembersInner) *NullableJobsJobJobSpecJobDataConfigServersMembersInner {
	return &NullableJobsJobJobSpecJobDataConfigServersMembersInner{value: val, isSet: true}
}

func (v NullableJobsJobJobSpecJobDataConfigServersMembersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobsJobJobSpecJobDataConfigServersMembersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


