/*
Severalnines ClusterControl REST API (V2)

REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

API version: OpenAPI specification v1.0.0
Contact: sales@severalnines.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ClustersAccount struct for ClustersAccount
type ClustersAccount struct {
	ClassName *string `json:"class_name,omitempty"`
	// e.g. \"john:ALL;pipas:INSERT\"
	Grants *string `json:"grants,omitempty"`
	// e.g. \"1.2.3.4\"
	HostAllow *string `json:"host_allow,omitempty"`
	OwnDatabase *string `json:"own_database,omitempty"`
	// e.g. \"testCreateDatabase.*:DELETE,TRUNCATE\"
	Privileges *string `json:"privileges,omitempty"`
	// e.g. \"pipas\"
	UserName *string `json:"user_name,omitempty"`
	Password *string `json:"password,omitempty"`
}

// NewClustersAccount instantiates a new ClustersAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClustersAccount() *ClustersAccount {
	this := ClustersAccount{}
	return &this
}

// NewClustersAccountWithDefaults instantiates a new ClustersAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClustersAccountWithDefaults() *ClustersAccount {
	this := ClustersAccount{}
	return &this
}

// GetClassName returns the ClassName field value if set, zero value otherwise.
func (o *ClustersAccount) GetClassName() string {
	if o == nil || isNil(o.ClassName) {
		var ret string
		return ret
	}
	return *o.ClassName
}

// GetClassNameOk returns a tuple with the ClassName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersAccount) GetClassNameOk() (*string, bool) {
	if o == nil || isNil(o.ClassName) {
    return nil, false
	}
	return o.ClassName, true
}

// HasClassName returns a boolean if a field has been set.
func (o *ClustersAccount) HasClassName() bool {
	if o != nil && !isNil(o.ClassName) {
		return true
	}

	return false
}

// SetClassName gets a reference to the given string and assigns it to the ClassName field.
func (o *ClustersAccount) SetClassName(v string) {
	o.ClassName = &v
}

// GetGrants returns the Grants field value if set, zero value otherwise.
func (o *ClustersAccount) GetGrants() string {
	if o == nil || isNil(o.Grants) {
		var ret string
		return ret
	}
	return *o.Grants
}

// GetGrantsOk returns a tuple with the Grants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersAccount) GetGrantsOk() (*string, bool) {
	if o == nil || isNil(o.Grants) {
    return nil, false
	}
	return o.Grants, true
}

// HasGrants returns a boolean if a field has been set.
func (o *ClustersAccount) HasGrants() bool {
	if o != nil && !isNil(o.Grants) {
		return true
	}

	return false
}

// SetGrants gets a reference to the given string and assigns it to the Grants field.
func (o *ClustersAccount) SetGrants(v string) {
	o.Grants = &v
}

// GetHostAllow returns the HostAllow field value if set, zero value otherwise.
func (o *ClustersAccount) GetHostAllow() string {
	if o == nil || isNil(o.HostAllow) {
		var ret string
		return ret
	}
	return *o.HostAllow
}

// GetHostAllowOk returns a tuple with the HostAllow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersAccount) GetHostAllowOk() (*string, bool) {
	if o == nil || isNil(o.HostAllow) {
    return nil, false
	}
	return o.HostAllow, true
}

// HasHostAllow returns a boolean if a field has been set.
func (o *ClustersAccount) HasHostAllow() bool {
	if o != nil && !isNil(o.HostAllow) {
		return true
	}

	return false
}

// SetHostAllow gets a reference to the given string and assigns it to the HostAllow field.
func (o *ClustersAccount) SetHostAllow(v string) {
	o.HostAllow = &v
}

// GetOwnDatabase returns the OwnDatabase field value if set, zero value otherwise.
func (o *ClustersAccount) GetOwnDatabase() string {
	if o == nil || isNil(o.OwnDatabase) {
		var ret string
		return ret
	}
	return *o.OwnDatabase
}

// GetOwnDatabaseOk returns a tuple with the OwnDatabase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersAccount) GetOwnDatabaseOk() (*string, bool) {
	if o == nil || isNil(o.OwnDatabase) {
    return nil, false
	}
	return o.OwnDatabase, true
}

// HasOwnDatabase returns a boolean if a field has been set.
func (o *ClustersAccount) HasOwnDatabase() bool {
	if o != nil && !isNil(o.OwnDatabase) {
		return true
	}

	return false
}

// SetOwnDatabase gets a reference to the given string and assigns it to the OwnDatabase field.
func (o *ClustersAccount) SetOwnDatabase(v string) {
	o.OwnDatabase = &v
}

// GetPrivileges returns the Privileges field value if set, zero value otherwise.
func (o *ClustersAccount) GetPrivileges() string {
	if o == nil || isNil(o.Privileges) {
		var ret string
		return ret
	}
	return *o.Privileges
}

// GetPrivilegesOk returns a tuple with the Privileges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersAccount) GetPrivilegesOk() (*string, bool) {
	if o == nil || isNil(o.Privileges) {
    return nil, false
	}
	return o.Privileges, true
}

// HasPrivileges returns a boolean if a field has been set.
func (o *ClustersAccount) HasPrivileges() bool {
	if o != nil && !isNil(o.Privileges) {
		return true
	}

	return false
}

// SetPrivileges gets a reference to the given string and assigns it to the Privileges field.
func (o *ClustersAccount) SetPrivileges(v string) {
	o.Privileges = &v
}

// GetUserName returns the UserName field value if set, zero value otherwise.
func (o *ClustersAccount) GetUserName() string {
	if o == nil || isNil(o.UserName) {
		var ret string
		return ret
	}
	return *o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersAccount) GetUserNameOk() (*string, bool) {
	if o == nil || isNil(o.UserName) {
    return nil, false
	}
	return o.UserName, true
}

// HasUserName returns a boolean if a field has been set.
func (o *ClustersAccount) HasUserName() bool {
	if o != nil && !isNil(o.UserName) {
		return true
	}

	return false
}

// SetUserName gets a reference to the given string and assigns it to the UserName field.
func (o *ClustersAccount) SetUserName(v string) {
	o.UserName = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *ClustersAccount) GetPassword() string {
	if o == nil || isNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersAccount) GetPasswordOk() (*string, bool) {
	if o == nil || isNil(o.Password) {
    return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *ClustersAccount) HasPassword() bool {
	if o != nil && !isNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *ClustersAccount) SetPassword(v string) {
	o.Password = &v
}

func (o ClustersAccount) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ClassName) {
		toSerialize["class_name"] = o.ClassName
	}
	if !isNil(o.Grants) {
		toSerialize["grants"] = o.Grants
	}
	if !isNil(o.HostAllow) {
		toSerialize["host_allow"] = o.HostAllow
	}
	if !isNil(o.OwnDatabase) {
		toSerialize["own_database"] = o.OwnDatabase
	}
	if !isNil(o.Privileges) {
		toSerialize["privileges"] = o.Privileges
	}
	if !isNil(o.UserName) {
		toSerialize["user_name"] = o.UserName
	}
	if !isNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return json.Marshal(toSerialize)
}

type NullableClustersAccount struct {
	value *ClustersAccount
	isSet bool
}

func (v NullableClustersAccount) Get() *ClustersAccount {
	return v.value
}

func (v *NullableClustersAccount) Set(val *ClustersAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableClustersAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableClustersAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClustersAccount(val *ClustersAccount) *NullableClustersAccount {
	return &NullableClustersAccount{value: val, isSet: true}
}

func (v NullableClustersAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClustersAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


