/*
Severalnines ClusterControl REST API (V2)

REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

API version: OpenAPI specification v1.0.0
Contact: sales@severalnines.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BackupResponseBackupRecordsInnerCloudLocationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackupResponseBackupRecordsInnerCloudLocationsInner{}

// BackupResponseBackupRecordsInnerCloudLocationsInner struct for BackupResponseBackupRecordsInnerCloudLocationsInner
type BackupResponseBackupRecordsInnerCloudLocationsInner struct {
	HostLocationUuid *string `json:"host_location_uuid,omitempty"`
}

// NewBackupResponseBackupRecordsInnerCloudLocationsInner instantiates a new BackupResponseBackupRecordsInnerCloudLocationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupResponseBackupRecordsInnerCloudLocationsInner() *BackupResponseBackupRecordsInnerCloudLocationsInner {
	this := BackupResponseBackupRecordsInnerCloudLocationsInner{}
	return &this
}

// NewBackupResponseBackupRecordsInnerCloudLocationsInnerWithDefaults instantiates a new BackupResponseBackupRecordsInnerCloudLocationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupResponseBackupRecordsInnerCloudLocationsInnerWithDefaults() *BackupResponseBackupRecordsInnerCloudLocationsInner {
	this := BackupResponseBackupRecordsInnerCloudLocationsInner{}
	return &this
}

// GetHostLocationUuid returns the HostLocationUuid field value if set, zero value otherwise.
func (o *BackupResponseBackupRecordsInnerCloudLocationsInner) GetHostLocationUuid() string {
	if o == nil || IsNil(o.HostLocationUuid) {
		var ret string
		return ret
	}
	return *o.HostLocationUuid
}

// GetHostLocationUuidOk returns a tuple with the HostLocationUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackupResponseBackupRecordsInnerCloudLocationsInner) GetHostLocationUuidOk() (*string, bool) {
	if o == nil || IsNil(o.HostLocationUuid) {
		return nil, false
	}
	return o.HostLocationUuid, true
}

// HasHostLocationUuid returns a boolean if a field has been set.
func (o *BackupResponseBackupRecordsInnerCloudLocationsInner) HasHostLocationUuid() bool {
	if o != nil && !IsNil(o.HostLocationUuid) {
		return true
	}

	return false
}

// SetHostLocationUuid gets a reference to the given string and assigns it to the HostLocationUuid field.
func (o *BackupResponseBackupRecordsInnerCloudLocationsInner) SetHostLocationUuid(v string) {
	o.HostLocationUuid = &v
}

func (o BackupResponseBackupRecordsInnerCloudLocationsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackupResponseBackupRecordsInnerCloudLocationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HostLocationUuid) {
		toSerialize["host_location_uuid"] = o.HostLocationUuid
	}
	return toSerialize, nil
}

type NullableBackupResponseBackupRecordsInnerCloudLocationsInner struct {
	value *BackupResponseBackupRecordsInnerCloudLocationsInner
	isSet bool
}

func (v NullableBackupResponseBackupRecordsInnerCloudLocationsInner) Get() *BackupResponseBackupRecordsInnerCloudLocationsInner {
	return v.value
}

func (v *NullableBackupResponseBackupRecordsInnerCloudLocationsInner) Set(val *BackupResponseBackupRecordsInnerCloudLocationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupResponseBackupRecordsInnerCloudLocationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupResponseBackupRecordsInnerCloudLocationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupResponseBackupRecordsInnerCloudLocationsInner(val *BackupResponseBackupRecordsInnerCloudLocationsInner) *NullableBackupResponseBackupRecordsInnerCloudLocationsInner {
	return &NullableBackupResponseBackupRecordsInnerCloudLocationsInner{value: val, isSet: true}
}

func (v NullableBackupResponseBackupRecordsInnerCloudLocationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupResponseBackupRecordsInnerCloudLocationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


