/*
Severalnines ClusterControl REST API (V2)

REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

API version: OpenAPI specification v1.0.0
Contact: sales@severalnines.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MaintenanceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MaintenanceResponse{}

// MaintenanceResponse struct for MaintenanceResponse
type MaintenanceResponse struct {
	MaintenanceRecords []MaintenanceResponseMaintenanceRecordsInner `json:"maintenance_records,omitempty"`
}

// NewMaintenanceResponse instantiates a new MaintenanceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMaintenanceResponse() *MaintenanceResponse {
	this := MaintenanceResponse{}
	return &this
}

// NewMaintenanceResponseWithDefaults instantiates a new MaintenanceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMaintenanceResponseWithDefaults() *MaintenanceResponse {
	this := MaintenanceResponse{}
	return &this
}

// GetMaintenanceRecords returns the MaintenanceRecords field value if set, zero value otherwise.
func (o *MaintenanceResponse) GetMaintenanceRecords() []MaintenanceResponseMaintenanceRecordsInner {
	if o == nil || IsNil(o.MaintenanceRecords) {
		var ret []MaintenanceResponseMaintenanceRecordsInner
		return ret
	}
	return o.MaintenanceRecords
}

// GetMaintenanceRecordsOk returns a tuple with the MaintenanceRecords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceResponse) GetMaintenanceRecordsOk() ([]MaintenanceResponseMaintenanceRecordsInner, bool) {
	if o == nil || IsNil(o.MaintenanceRecords) {
		return nil, false
	}
	return o.MaintenanceRecords, true
}

// HasMaintenanceRecords returns a boolean if a field has been set.
func (o *MaintenanceResponse) HasMaintenanceRecords() bool {
	if o != nil && !IsNil(o.MaintenanceRecords) {
		return true
	}

	return false
}

// SetMaintenanceRecords gets a reference to the given []MaintenanceResponseMaintenanceRecordsInner and assigns it to the MaintenanceRecords field.
func (o *MaintenanceResponse) SetMaintenanceRecords(v []MaintenanceResponseMaintenanceRecordsInner) {
	o.MaintenanceRecords = v
}

func (o MaintenanceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MaintenanceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaintenanceRecords) {
		toSerialize["maintenance_records"] = o.MaintenanceRecords
	}
	return toSerialize, nil
}

type NullableMaintenanceResponse struct {
	value *MaintenanceResponse
	isSet bool
}

func (v NullableMaintenanceResponse) Get() *MaintenanceResponse {
	return v.value
}

func (v *NullableMaintenanceResponse) Set(val *MaintenanceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMaintenanceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMaintenanceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMaintenanceResponse(val *MaintenanceResponse) *NullableMaintenanceResponse {
	return &NullableMaintenanceResponse{value: val, isSet: true}
}

func (v NullableMaintenanceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMaintenanceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


