/*
Severalnines ClusterControl REST API (V2)

REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

API version: OpenAPI specification v1.0.0
Contact: sales@severalnines.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UsersUserGroupsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersUserGroupsInner{}

// UsersUserGroupsInner struct for UsersUserGroupsInner
type UsersUserGroupsInner struct {
	ClassName *string `json:"class_name,omitempty"`
	GroupName *string `json:"group_name,omitempty"`
	GroupId *int32 `json:"group_id,omitempty"`
}

// NewUsersUserGroupsInner instantiates a new UsersUserGroupsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersUserGroupsInner() *UsersUserGroupsInner {
	this := UsersUserGroupsInner{}
	return &this
}

// NewUsersUserGroupsInnerWithDefaults instantiates a new UsersUserGroupsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersUserGroupsInnerWithDefaults() *UsersUserGroupsInner {
	this := UsersUserGroupsInner{}
	return &this
}

// GetClassName returns the ClassName field value if set, zero value otherwise.
func (o *UsersUserGroupsInner) GetClassName() string {
	if o == nil || IsNil(o.ClassName) {
		var ret string
		return ret
	}
	return *o.ClassName
}

// GetClassNameOk returns a tuple with the ClassName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersUserGroupsInner) GetClassNameOk() (*string, bool) {
	if o == nil || IsNil(o.ClassName) {
		return nil, false
	}
	return o.ClassName, true
}

// HasClassName returns a boolean if a field has been set.
func (o *UsersUserGroupsInner) HasClassName() bool {
	if o != nil && !IsNil(o.ClassName) {
		return true
	}

	return false
}

// SetClassName gets a reference to the given string and assigns it to the ClassName field.
func (o *UsersUserGroupsInner) SetClassName(v string) {
	o.ClassName = &v
}

// GetGroupName returns the GroupName field value if set, zero value otherwise.
func (o *UsersUserGroupsInner) GetGroupName() string {
	if o == nil || IsNil(o.GroupName) {
		var ret string
		return ret
	}
	return *o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersUserGroupsInner) GetGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.GroupName) {
		return nil, false
	}
	return o.GroupName, true
}

// HasGroupName returns a boolean if a field has been set.
func (o *UsersUserGroupsInner) HasGroupName() bool {
	if o != nil && !IsNil(o.GroupName) {
		return true
	}

	return false
}

// SetGroupName gets a reference to the given string and assigns it to the GroupName field.
func (o *UsersUserGroupsInner) SetGroupName(v string) {
	o.GroupName = &v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *UsersUserGroupsInner) GetGroupId() int32 {
	if o == nil || IsNil(o.GroupId) {
		var ret int32
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersUserGroupsInner) GetGroupIdOk() (*int32, bool) {
	if o == nil || IsNil(o.GroupId) {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *UsersUserGroupsInner) HasGroupId() bool {
	if o != nil && !IsNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given int32 and assigns it to the GroupId field.
func (o *UsersUserGroupsInner) SetGroupId(v int32) {
	o.GroupId = &v
}

func (o UsersUserGroupsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersUserGroupsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClassName) {
		toSerialize["class_name"] = o.ClassName
	}
	if !IsNil(o.GroupName) {
		toSerialize["group_name"] = o.GroupName
	}
	if !IsNil(o.GroupId) {
		toSerialize["group_id"] = o.GroupId
	}
	return toSerialize, nil
}

type NullableUsersUserGroupsInner struct {
	value *UsersUserGroupsInner
	isSet bool
}

func (v NullableUsersUserGroupsInner) Get() *UsersUserGroupsInner {
	return v.value
}

func (v *NullableUsersUserGroupsInner) Set(val *UsersUserGroupsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersUserGroupsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersUserGroupsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersUserGroupsInner(val *UsersUserGroupsInner) *NullableUsersUserGroupsInner {
	return &NullableUsersUserGroupsInner{value: val, isSet: true}
}

func (v NullableUsersUserGroupsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersUserGroupsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


