# coding: utf-8

"""
    Severalnines ClusterControl REST API (V2)

    REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

    The version of the OpenAPI document: OpenAPI specification v1.0.0
    Contact: sales@severalnines.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_cc_client.models.stat_prometheus import StatPrometheus

class TestStatPrometheus(unittest.TestCase):
    """StatPrometheus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatPrometheus:
        """Test StatPrometheus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatPrometheus`
        """
        model = StatPrometheus()
        if include_optional:
            return StatPrometheus(
                operation = '/prometheus',
                cluster_id = 56,
                cluster_name = '',
                queries = [
                    openapi_cc_client.models.stat_prometheus_queries_inner.StatPrometheus_queries_inner(
                        query = '', 
                        step = 56, )
                    ],
                start = 56,
                end = 56,
                step = 56,
                returnfrom = 56
            )
        else:
            return StatPrometheus(
                operation = '/prometheus',
        )
        """

    def testStatPrometheus(self):
        """Test StatPrometheus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
