# coding: utf-8

"""
    Severalnines ClusterControl REST API (V2)

    REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.

    The version of the OpenAPI document: OpenAPI specification v1.0.0
    Contact: sales@severalnines.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_cc_client.models.backup_response_backup_records_inner_cluster import BackupResponseBackupRecordsInnerCluster

class TestBackupResponseBackupRecordsInnerCluster(unittest.TestCase):
    """BackupResponseBackupRecordsInnerCluster unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BackupResponseBackupRecordsInnerCluster:
        """Test BackupResponseBackupRecordsInnerCluster
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BackupResponseBackupRecordsInnerCluster`
        """
        model = BackupResponseBackupRecordsInnerCluster()
        if include_optional:
            return BackupResponseBackupRecordsInnerCluster(
                cluster_name = '',
                cluster_id = 56,
                cluster_auto_recovery = True,
                maintenance_mode_active = True,
                maintenance_periods = [
                    openapi_cc_client.models.backup_response_backup_records_inner_cluster_maintenance_periods_inner.BackupResponse_backup_records_inner_cluster_maintenance_periods_inner(
                        uuid = '', 
                        initiate = '', 
                        deadline = '', 
                        is_active = True, 
                        reason = '', )
                    ]
            )
        else:
            return BackupResponseBackupRecordsInnerCluster(
        )
        """

    def testBackupResponseBackupRecordsInnerCluster(self):
        """Test BackupResponseBackupRecordsInnerCluster"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
