/*
 * Severalnines ClusterControl
 * This is a ...
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sales@severalnines.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.ccapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobsJobJobSpecJobDataUploadBackupDataToCloudStorage
 */
public class JobsJobJobSpecJobDataUploadBackupDataToCloudStorageTest {
    private final JobsJobJobSpecJobDataUploadBackupDataToCloudStorage model = new JobsJobJobSpecJobDataUploadBackupDataToCloudStorage();

    /**
     * Model tests for JobsJobJobSpecJobDataUploadBackupDataToCloudStorage
     */
    @Test
    public void testJobsJobJobSpecJobDataUploadBackupDataToCloudStorage() {
        // TODO: test JobsJobJobSpecJobDataUploadBackupDataToCloudStorage
    }

    /**
     * Test the property 'backupRetention'
     */
    @Test
    public void backupRetentionTest() {
        // TODO: test backupRetention
    }

    /**
     * Test the property 'bucket'
     */
    @Test
    public void bucketTest() {
        // TODO: test bucket
    }

    /**
     * Test the property 'cloudStorageCredentialsId'
     */
    @Test
    public void cloudStorageCredentialsIdTest() {
        // TODO: test cloudStorageCredentialsId
    }

    /**
     * Test the property 'cloudStorageProvider'
     */
    @Test
    public void cloudStorageProviderTest() {
        // TODO: test cloudStorageProvider
    }

    /**
     * Test the property 'cloudStorageService'
     */
    @Test
    public void cloudStorageServiceTest() {
        // TODO: test cloudStorageService
    }

    /**
     * Test the property 'deleteAfterUpload'
     */
    @Test
    public void deleteAfterUploadTest() {
        // TODO: test deleteAfterUpload
    }

}
