/*
 * Severalnines ClusterControl REST API (V2)
 * REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.
 *
 * The version of the OpenAPI document: OpenAPI specification v1.0.0
 * Contact: sales@severalnines.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.ccapi.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.ccapi.client.JSON;

/**
 * BackupResponseBackupRecordsInnerCloudLocationsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-25T20:06:39.466573-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class BackupResponseBackupRecordsInnerCloudLocationsInner {
  public static final String SERIALIZED_NAME_HOST_LOCATION_UUID = "host_location_uuid";
  @SerializedName(SERIALIZED_NAME_HOST_LOCATION_UUID)
  @javax.annotation.Nullable
  private String hostLocationUuid;

  public BackupResponseBackupRecordsInnerCloudLocationsInner() {
  }

  public BackupResponseBackupRecordsInnerCloudLocationsInner hostLocationUuid(@javax.annotation.Nullable String hostLocationUuid) {
    this.hostLocationUuid = hostLocationUuid;
    return this;
  }

  /**
   * Get hostLocationUuid
   * @return hostLocationUuid
   */
  @javax.annotation.Nullable
  public String getHostLocationUuid() {
    return hostLocationUuid;
  }

  public void setHostLocationUuid(@javax.annotation.Nullable String hostLocationUuid) {
    this.hostLocationUuid = hostLocationUuid;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackupResponseBackupRecordsInnerCloudLocationsInner backupResponseBackupRecordsInnerCloudLocationsInner = (BackupResponseBackupRecordsInnerCloudLocationsInner) o;
    return Objects.equals(this.hostLocationUuid, backupResponseBackupRecordsInnerCloudLocationsInner.hostLocationUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hostLocationUuid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackupResponseBackupRecordsInnerCloudLocationsInner {\n");
    sb.append("    hostLocationUuid: ").append(toIndentedString(hostLocationUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("host_location_uuid"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BackupResponseBackupRecordsInnerCloudLocationsInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BackupResponseBackupRecordsInnerCloudLocationsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BackupResponseBackupRecordsInnerCloudLocationsInner is not found in the empty JSON string", BackupResponseBackupRecordsInnerCloudLocationsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BackupResponseBackupRecordsInnerCloudLocationsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BackupResponseBackupRecordsInnerCloudLocationsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("host_location_uuid") != null && !jsonObj.get("host_location_uuid").isJsonNull()) && !jsonObj.get("host_location_uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `host_location_uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("host_location_uuid").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BackupResponseBackupRecordsInnerCloudLocationsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BackupResponseBackupRecordsInnerCloudLocationsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BackupResponseBackupRecordsInnerCloudLocationsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BackupResponseBackupRecordsInnerCloudLocationsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<BackupResponseBackupRecordsInnerCloudLocationsInner>() {
           @Override
           public void write(JsonWriter out, BackupResponseBackupRecordsInnerCloudLocationsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BackupResponseBackupRecordsInnerCloudLocationsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BackupResponseBackupRecordsInnerCloudLocationsInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BackupResponseBackupRecordsInnerCloudLocationsInner
   * @throws IOException if the JSON string is invalid with respect to BackupResponseBackupRecordsInnerCloudLocationsInner
   */
  public static BackupResponseBackupRecordsInnerCloudLocationsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BackupResponseBackupRecordsInnerCloudLocationsInner.class);
  }

  /**
   * Convert an instance of BackupResponseBackupRecordsInnerCloudLocationsInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

