/*
 * Severalnines ClusterControl REST API (V2)
 * REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.
 *
 * The version of the OpenAPI document: OpenAPI specification v1.0.0
 * Contact: sales@severalnines.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.ccapi.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.ccapi.client.JSON;

/**
 * ClustersAccount
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-25T20:06:39.466573-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class ClustersAccount {
  /**
   * Gets or Sets className
   */
  @JsonAdapter(ClassNameEnum.Adapter.class)
  public enum ClassNameEnum {
    CMON_ACCOUNT("CmonAccount");

    private String value;

    ClassNameEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ClassNameEnum fromValue(String value) {
      for (ClassNameEnum b : ClassNameEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ClassNameEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ClassNameEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ClassNameEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ClassNameEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ClassNameEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CLASS_NAME = "class_name";
  @SerializedName(SERIALIZED_NAME_CLASS_NAME)
  @javax.annotation.Nullable
  private ClassNameEnum className;

  public static final String SERIALIZED_NAME_GRANTS = "grants";
  @SerializedName(SERIALIZED_NAME_GRANTS)
  @javax.annotation.Nullable
  private String grants;

  public static final String SERIALIZED_NAME_HOST_ALLOW = "host_allow";
  @SerializedName(SERIALIZED_NAME_HOST_ALLOW)
  @javax.annotation.Nullable
  private String hostAllow;

  public static final String SERIALIZED_NAME_OWN_DATABASE = "own_database";
  @SerializedName(SERIALIZED_NAME_OWN_DATABASE)
  @javax.annotation.Nullable
  private String ownDatabase;

  public static final String SERIALIZED_NAME_PRIVILEGES = "privileges";
  @SerializedName(SERIALIZED_NAME_PRIVILEGES)
  @javax.annotation.Nullable
  private String privileges;

  public static final String SERIALIZED_NAME_USER_NAME = "user_name";
  @SerializedName(SERIALIZED_NAME_USER_NAME)
  @javax.annotation.Nullable
  private String userName;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  @javax.annotation.Nullable
  private String password;

  public ClustersAccount() {
  }

  public ClustersAccount className(@javax.annotation.Nullable ClassNameEnum className) {
    this.className = className;
    return this;
  }

  /**
   * Get className
   * @return className
   */
  @javax.annotation.Nullable
  public ClassNameEnum getClassName() {
    return className;
  }

  public void setClassName(@javax.annotation.Nullable ClassNameEnum className) {
    this.className = className;
  }


  public ClustersAccount grants(@javax.annotation.Nullable String grants) {
    this.grants = grants;
    return this;
  }

  /**
   * e.g. \&quot;john:ALL;pipas:INSERT\&quot;
   * @return grants
   */
  @javax.annotation.Nullable
  public String getGrants() {
    return grants;
  }

  public void setGrants(@javax.annotation.Nullable String grants) {
    this.grants = grants;
  }


  public ClustersAccount hostAllow(@javax.annotation.Nullable String hostAllow) {
    this.hostAllow = hostAllow;
    return this;
  }

  /**
   * e.g. \&quot;1.2.3.4\&quot;
   * @return hostAllow
   */
  @javax.annotation.Nullable
  public String getHostAllow() {
    return hostAllow;
  }

  public void setHostAllow(@javax.annotation.Nullable String hostAllow) {
    this.hostAllow = hostAllow;
  }


  public ClustersAccount ownDatabase(@javax.annotation.Nullable String ownDatabase) {
    this.ownDatabase = ownDatabase;
    return this;
  }

  /**
   * Get ownDatabase
   * @return ownDatabase
   */
  @javax.annotation.Nullable
  public String getOwnDatabase() {
    return ownDatabase;
  }

  public void setOwnDatabase(@javax.annotation.Nullable String ownDatabase) {
    this.ownDatabase = ownDatabase;
  }


  public ClustersAccount privileges(@javax.annotation.Nullable String privileges) {
    this.privileges = privileges;
    return this;
  }

  /**
   * e.g. \&quot;testCreateDatabase.*:DELETE,TRUNCATE\&quot;
   * @return privileges
   */
  @javax.annotation.Nullable
  public String getPrivileges() {
    return privileges;
  }

  public void setPrivileges(@javax.annotation.Nullable String privileges) {
    this.privileges = privileges;
  }


  public ClustersAccount userName(@javax.annotation.Nullable String userName) {
    this.userName = userName;
    return this;
  }

  /**
   * e.g. \&quot;pipas\&quot;
   * @return userName
   */
  @javax.annotation.Nullable
  public String getUserName() {
    return userName;
  }

  public void setUserName(@javax.annotation.Nullable String userName) {
    this.userName = userName;
  }


  public ClustersAccount password(@javax.annotation.Nullable String password) {
    this.password = password;
    return this;
  }

  /**
   * Get password
   * @return password
   */
  @javax.annotation.Nullable
  public String getPassword() {
    return password;
  }

  public void setPassword(@javax.annotation.Nullable String password) {
    this.password = password;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClustersAccount clustersAccount = (ClustersAccount) o;
    return Objects.equals(this.className, clustersAccount.className) &&
        Objects.equals(this.grants, clustersAccount.grants) &&
        Objects.equals(this.hostAllow, clustersAccount.hostAllow) &&
        Objects.equals(this.ownDatabase, clustersAccount.ownDatabase) &&
        Objects.equals(this.privileges, clustersAccount.privileges) &&
        Objects.equals(this.userName, clustersAccount.userName) &&
        Objects.equals(this.password, clustersAccount.password);
  }

  @Override
  public int hashCode() {
    return Objects.hash(className, grants, hostAllow, ownDatabase, privileges, userName, password);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClustersAccount {\n");
    sb.append("    className: ").append(toIndentedString(className)).append("\n");
    sb.append("    grants: ").append(toIndentedString(grants)).append("\n");
    sb.append("    hostAllow: ").append(toIndentedString(hostAllow)).append("\n");
    sb.append("    ownDatabase: ").append(toIndentedString(ownDatabase)).append("\n");
    sb.append("    privileges: ").append(toIndentedString(privileges)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("class_name", "grants", "host_allow", "own_database", "privileges", "user_name", "password"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ClustersAccount
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ClustersAccount.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ClustersAccount is not found in the empty JSON string", ClustersAccount.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ClustersAccount.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ClustersAccount` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("class_name") != null && !jsonObj.get("class_name").isJsonNull()) && !jsonObj.get("class_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `class_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("class_name").toString()));
      }
      // validate the optional field `class_name`
      if (jsonObj.get("class_name") != null && !jsonObj.get("class_name").isJsonNull()) {
        ClassNameEnum.validateJsonElement(jsonObj.get("class_name"));
      }
      if ((jsonObj.get("grants") != null && !jsonObj.get("grants").isJsonNull()) && !jsonObj.get("grants").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `grants` to be a primitive type in the JSON string but got `%s`", jsonObj.get("grants").toString()));
      }
      if ((jsonObj.get("host_allow") != null && !jsonObj.get("host_allow").isJsonNull()) && !jsonObj.get("host_allow").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `host_allow` to be a primitive type in the JSON string but got `%s`", jsonObj.get("host_allow").toString()));
      }
      if ((jsonObj.get("own_database") != null && !jsonObj.get("own_database").isJsonNull()) && !jsonObj.get("own_database").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `own_database` to be a primitive type in the JSON string but got `%s`", jsonObj.get("own_database").toString()));
      }
      if ((jsonObj.get("privileges") != null && !jsonObj.get("privileges").isJsonNull()) && !jsonObj.get("privileges").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `privileges` to be a primitive type in the JSON string but got `%s`", jsonObj.get("privileges").toString()));
      }
      if ((jsonObj.get("user_name") != null && !jsonObj.get("user_name").isJsonNull()) && !jsonObj.get("user_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `user_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_name").toString()));
      }
      if ((jsonObj.get("password") != null && !jsonObj.get("password").isJsonNull()) && !jsonObj.get("password").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `password` to be a primitive type in the JSON string but got `%s`", jsonObj.get("password").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ClustersAccount.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ClustersAccount' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ClustersAccount> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ClustersAccount.class));

       return (TypeAdapter<T>) new TypeAdapter<ClustersAccount>() {
           @Override
           public void write(JsonWriter out, ClustersAccount value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ClustersAccount read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ClustersAccount given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ClustersAccount
   * @throws IOException if the JSON string is invalid with respect to ClustersAccount
   */
  public static ClustersAccount fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ClustersAccount.class);
  }

  /**
   * Convert an instance of ClustersAccount to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

