/*
 * Severalnines ClusterControl REST API (V2)
 * REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.
 *
 * The version of the OpenAPI document: OpenAPI specification v1.0.0
 * Contact: sales@severalnines.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.ccapi.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.ccapi.client.model.JobsJobJobSpecJobDataConfigServersMembersInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.ccapi.client.JSON;

/**
 * JobsJobJobSpecJobDataConfigServers
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-25T20:06:39.466573-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class JobsJobJobSpecJobDataConfigServers {
  public static final String SERIALIZED_NAME_RS = "rs";
  @SerializedName(SERIALIZED_NAME_RS)
  @javax.annotation.Nullable
  private String rs;

  public static final String SERIALIZED_NAME_MEMBERS = "members";
  @SerializedName(SERIALIZED_NAME_MEMBERS)
  @javax.annotation.Nullable
  private List<JobsJobJobSpecJobDataConfigServersMembersInner> members = new ArrayList<>();

  public JobsJobJobSpecJobDataConfigServers() {
  }

  public JobsJobJobSpecJobDataConfigServers rs(@javax.annotation.Nullable String rs) {
    this.rs = rs;
    return this;
  }

  /**
   * Get rs
   * @return rs
   */
  @javax.annotation.Nullable
  public String getRs() {
    return rs;
  }

  public void setRs(@javax.annotation.Nullable String rs) {
    this.rs = rs;
  }


  public JobsJobJobSpecJobDataConfigServers members(@javax.annotation.Nullable List<JobsJobJobSpecJobDataConfigServersMembersInner> members) {
    this.members = members;
    return this;
  }

  public JobsJobJobSpecJobDataConfigServers addMembersItem(JobsJobJobSpecJobDataConfigServersMembersInner membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<>();
    }
    this.members.add(membersItem);
    return this;
  }

  /**
   * Get members
   * @return members
   */
  @javax.annotation.Nullable
  public List<JobsJobJobSpecJobDataConfigServersMembersInner> getMembers() {
    return members;
  }

  public void setMembers(@javax.annotation.Nullable List<JobsJobJobSpecJobDataConfigServersMembersInner> members) {
    this.members = members;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobsJobJobSpecJobDataConfigServers jobsJobJobSpecJobDataConfigServers = (JobsJobJobSpecJobDataConfigServers) o;
    return Objects.equals(this.rs, jobsJobJobSpecJobDataConfigServers.rs) &&
        Objects.equals(this.members, jobsJobJobSpecJobDataConfigServers.members);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rs, members);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobsJobJobSpecJobDataConfigServers {\n");
    sb.append("    rs: ").append(toIndentedString(rs)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("rs", "members"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to JobsJobJobSpecJobDataConfigServers
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!JobsJobJobSpecJobDataConfigServers.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in JobsJobJobSpecJobDataConfigServers is not found in the empty JSON string", JobsJobJobSpecJobDataConfigServers.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!JobsJobJobSpecJobDataConfigServers.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `JobsJobJobSpecJobDataConfigServers` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("rs") != null && !jsonObj.get("rs").isJsonNull()) && !jsonObj.get("rs").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `rs` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rs").toString()));
      }
      if (jsonObj.get("members") != null && !jsonObj.get("members").isJsonNull()) {
        JsonArray jsonArraymembers = jsonObj.getAsJsonArray("members");
        if (jsonArraymembers != null) {
          // ensure the json data is an array
          if (!jsonObj.get("members").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `members` to be an array in the JSON string but got `%s`", jsonObj.get("members").toString()));
          }

          // validate the optional field `members` (array)
          for (int i = 0; i < jsonArraymembers.size(); i++) {
            JobsJobJobSpecJobDataConfigServersMembersInner.validateJsonElement(jsonArraymembers.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JobsJobJobSpecJobDataConfigServers.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JobsJobJobSpecJobDataConfigServers' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JobsJobJobSpecJobDataConfigServers> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JobsJobJobSpecJobDataConfigServers.class));

       return (TypeAdapter<T>) new TypeAdapter<JobsJobJobSpecJobDataConfigServers>() {
           @Override
           public void write(JsonWriter out, JobsJobJobSpecJobDataConfigServers value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JobsJobJobSpecJobDataConfigServers read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of JobsJobJobSpecJobDataConfigServers given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of JobsJobJobSpecJobDataConfigServers
   * @throws IOException if the JSON string is invalid with respect to JobsJobJobSpecJobDataConfigServers
   */
  public static JobsJobJobSpecJobDataConfigServers fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JobsJobJobSpecJobDataConfigServers.class);
  }

  /**
   * Convert an instance of JobsJobJobSpecJobDataConfigServers to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

