/*
 * Severalnines ClusterControl REST API (V2)
 * REST API (V2) specification for ClusterControl - AI Powered Database automation tool for multi/hybrid cloud database deployment.
 *
 * The version of the OpenAPI document: OpenAPI specification v1.0.0
 * Contact: sales@severalnines.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.ccapi.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.ccapi.client.model.BackupResponseBackupRecordsInnerCluster;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.ccapi.client.JSON;

/**
 * MaintenanceResponseMaintenanceRecordsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-25T20:06:39.466573-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class MaintenanceResponseMaintenanceRecordsInner {
  public static final String SERIALIZED_NAME_CLUSTER_ID = "cluster_id";
  @SerializedName(SERIALIZED_NAME_CLUSTER_ID)
  @javax.annotation.Nullable
  private Integer clusterId;

  public static final String SERIALIZED_NAME_IS_ACTIVE = "is_active";
  @SerializedName(SERIALIZED_NAME_IS_ACTIVE)
  @javax.annotation.Nullable
  private Boolean isActive;

  public static final String SERIALIZED_NAME_CLUSTER = "cluster";
  @SerializedName(SERIALIZED_NAME_CLUSTER)
  @javax.annotation.Nullable
  private BackupResponseBackupRecordsInnerCluster cluster;

  public MaintenanceResponseMaintenanceRecordsInner() {
  }

  public MaintenanceResponseMaintenanceRecordsInner clusterId(@javax.annotation.Nullable Integer clusterId) {
    this.clusterId = clusterId;
    return this;
  }

  /**
   * Get clusterId
   * @return clusterId
   */
  @javax.annotation.Nullable
  public Integer getClusterId() {
    return clusterId;
  }

  public void setClusterId(@javax.annotation.Nullable Integer clusterId) {
    this.clusterId = clusterId;
  }


  public MaintenanceResponseMaintenanceRecordsInner isActive(@javax.annotation.Nullable Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

  /**
   * Get isActive
   * @return isActive
   */
  @javax.annotation.Nullable
  public Boolean getIsActive() {
    return isActive;
  }

  public void setIsActive(@javax.annotation.Nullable Boolean isActive) {
    this.isActive = isActive;
  }


  public MaintenanceResponseMaintenanceRecordsInner cluster(@javax.annotation.Nullable BackupResponseBackupRecordsInnerCluster cluster) {
    this.cluster = cluster;
    return this;
  }

  /**
   * Get cluster
   * @return cluster
   */
  @javax.annotation.Nullable
  public BackupResponseBackupRecordsInnerCluster getCluster() {
    return cluster;
  }

  public void setCluster(@javax.annotation.Nullable BackupResponseBackupRecordsInnerCluster cluster) {
    this.cluster = cluster;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MaintenanceResponseMaintenanceRecordsInner maintenanceResponseMaintenanceRecordsInner = (MaintenanceResponseMaintenanceRecordsInner) o;
    return Objects.equals(this.clusterId, maintenanceResponseMaintenanceRecordsInner.clusterId) &&
        Objects.equals(this.isActive, maintenanceResponseMaintenanceRecordsInner.isActive) &&
        Objects.equals(this.cluster, maintenanceResponseMaintenanceRecordsInner.cluster);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clusterId, isActive, cluster);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MaintenanceResponseMaintenanceRecordsInner {\n");
    sb.append("    clusterId: ").append(toIndentedString(clusterId)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    cluster: ").append(toIndentedString(cluster)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("cluster_id", "is_active", "cluster"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MaintenanceResponseMaintenanceRecordsInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MaintenanceResponseMaintenanceRecordsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MaintenanceResponseMaintenanceRecordsInner is not found in the empty JSON string", MaintenanceResponseMaintenanceRecordsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MaintenanceResponseMaintenanceRecordsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `MaintenanceResponseMaintenanceRecordsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `cluster`
      if (jsonObj.get("cluster") != null && !jsonObj.get("cluster").isJsonNull()) {
        BackupResponseBackupRecordsInnerCluster.validateJsonElement(jsonObj.get("cluster"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MaintenanceResponseMaintenanceRecordsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MaintenanceResponseMaintenanceRecordsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MaintenanceResponseMaintenanceRecordsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MaintenanceResponseMaintenanceRecordsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<MaintenanceResponseMaintenanceRecordsInner>() {
           @Override
           public void write(JsonWriter out, MaintenanceResponseMaintenanceRecordsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MaintenanceResponseMaintenanceRecordsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MaintenanceResponseMaintenanceRecordsInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MaintenanceResponseMaintenanceRecordsInner
   * @throws IOException if the JSON string is invalid with respect to MaintenanceResponseMaintenanceRecordsInner
   */
  public static MaintenanceResponseMaintenanceRecordsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MaintenanceResponseMaintenanceRecordsInner.class);
  }

  /**
   * Convert an instance of MaintenanceResponseMaintenanceRecordsInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

